### ISSUE TITLE
Canvas container undefined in Vue application

### ISSUE THREAD

**Issue by ghost** [ismms-himc/clustergrammer-gl#3]
First and foremost this is an amazing library. Thank you for your work.

I am trying to implement clustergrammer-gl in a Vue application but I am running into errors.

```
clustergrammer-gl.node.js?3773:42556 Uncaught TypeError: Cannot read property '0' of undefined
    at clustergrammer_gl (clustergrammer-gl.node.js?3773:42556)
    at VueComponent.renderHeatmap (BxHeatmap.vue?de86:45)
    at <anonymous>:1:6
```

coming from this line: 
var canvas_container = d3.select(container).select('.canvas-container')[0][0];

```
import * as clustergrammer from 'clustergrammer-gl';
this.heatmapInstance = clustergrammer({
        container: '#heatmap',
        network: this.heatmapJSON,
        viz_height: 1000,
        viz_width: 1000,
      });
```
where this.heatmapJSON is a viz_json generated from clustergrammer-py.

It works with the clustergrammer-js but not the gl lib.

Please let me know if theres something I am not doing correctly.

**Comment by cornhundred** [comment]
Hi @lichri11. It looks like d3 is not able to select the container since you are passing in a string with the id of the element. You can try to pass the container element like this (see https://github.com/ismms-himc/clustergrammer-gl/blob/master/index.html#L31):

`var inst_container = document.getElementById('something');`

```
    d3.json(filename, function(network){
      args = {};
      args.network = network;
      args.container=inst_container;
      args.viz_width=inst_width;
      args.viz_height=inst_width;
      cgm = Clustergrammer2(args);
    });
```

Let us know if that helped.

**Comment by cornhundred** [comment]
I'm closing the issue due to inactivity, please raise again if needed.
