### ISSUE TITLE
custom matrix tile color scheme

### ISSUE THREAD

**Issue by cornhundred** [ismms-himc/clustergrammer-gl#33]
**Is your feature request related to a problem? Please describe.**
I want to be able to change the color scheme - currently it is only red/blue for positive/negative values, respectively

**Describe the solution you'd like**
I would like to be able to pass in two colors in the arguments JSON (e.g. named colors or hexcode) and have those override the positive/negative colors.

**Additional context**
This issue is necessary for resolving this issue in Clustergrammer2 https://github.com/ismms-himc/clustergrammer2/issues/39

**Comment by chenmengyu** [comment]
I also have this problem.

**Comment by cornhundred** [comment]
This feature has been added as of Clustergrammer-GL version 0.16.0. The matrix colors can be defined in the visualization JSON network object

```
      // set matrix colors
      network.matrix_colors = {}
      network.matrix_colors.pos = 'red'
      network.matrix_colors.neg = 'blue'
```

@chenmengyu
