### ISSUE TITLE
npm packaging

### ISSUE THREAD

**Issue by pjb7687** [ismms-himc/clustergrammer-gl#52]
Hello, I would like to try `clustergrammer-gl` in my application - may I ask you have a plan to publish this to npm registry soon?

**Comment by cornhundred** [comment]
Hi @pjb7687 yes we've published to NPM here https://www.npmjs.com/package/clustergrammer-gl

Please let us know if you have any questions

**Comment by pjb7687** [comment]
Thanks a lot!
